--
-- Đang đổ dữ liệu cho bảng `province`
--

INSERT INTO `cities` (`id`, `name_city`) VALUES
(92, 'Thành phố Cần Thơ'),
(1, 'Thành phố Hà Nội'),
(31, 'Thành phố Hải Phòng'),
(79, 'Thành phố Hồ Chí Minh'),
(48, 'Thành phố Đà Nẵng'),
(89, 'Tỉnh An Giang'),
(77, 'Tỉnh Bà Rịa - Vũng Tàu'),
(24, 'Tỉnh Bắc Giang'),
(6, 'Tỉnh Bắc Kạn'),
(95, 'Tỉnh Bạc Liêu'),
(27, 'Tỉnh Bắc Ninh'),
(83, 'Tỉnh Bến Tre'),
(74, 'Tỉnh Bình Dương'),
(70, 'Tỉnh Bình Phước'),
(60, 'Tỉnh Bình Thuận'),
(52, 'Tỉnh Bình Định'),
(96, 'Tỉnh Cà Mau'),
(4, 'Tỉnh Cao Bằng'),
(64, 'Tỉnh Gia Lai'),
(2, 'Tỉnh Hà Giang'),
(35, 'Tỉnh Hà Nam'),
(42, 'Tỉnh Hà Tĩnh'),
(30, 'Tỉnh Hải Dương'),
(93, 'Tỉnh Hậu Giang'),
(17, 'Tỉnh Hoà Bình'),
(33, 'Tỉnh Hưng Yên'),
(56, 'Tỉnh Khánh Hòa'),
(91, 'Tỉnh Kiên Giang'),
(62, 'Tỉnh Kon Tum'),
(12, 'Tỉnh Lai Châu'),
(68, 'Tỉnh Lâm Đồng'),
(20, 'Tỉnh Lạng Sơn'),
(10, 'Tỉnh Lào Cai'),
(80, 'Tỉnh Long An'),
(36, 'Tỉnh Nam Định'),
(40, 'Tỉnh Nghệ An'),
(37, 'Tỉnh Ninh Bình'),
(58, 'Tỉnh Ninh Thuận'),
(25, 'Tỉnh Phú Thọ'),
(54, 'Tỉnh Phú Yên'),
(44, 'Tỉnh Quảng Bình'),
(49, 'Tỉnh Quảng Nam'),
(51, 'Tỉnh Quảng Ngãi'),
(22, 'Tỉnh Quảng Ninh'),
(45, 'Tỉnh Quảng Trị'),
(94, 'Tỉnh Sóc Trăng'),
(14, 'Tỉnh Sơn La'),
(72, 'Tỉnh Tây Ninh'),
(34, 'Tỉnh Thái Bình'),
(19, 'Tỉnh Thái Nguyên'),
(38, 'Tỉnh Thanh Hóa'),
(46, 'Tỉnh Thừa Thiên Huế'),
(82, 'Tỉnh Tiền Giang'),
(84, 'Tỉnh Trà Vinh'),
(8, 'Tỉnh Tuyên Quang'),
(86, 'Tỉnh Vĩnh Long'),
(26, 'Tỉnh Vĩnh Phúc'),
(15, 'Tỉnh Yên Bái'),
(66, 'Tỉnh Đắk Lắk'),
(67, 'Tỉnh Đắk Nông'),
(11, 'Tỉnh Điện Biên'),
(75, 'Tỉnh Đồng Nai'),
(87, 'Tỉnh Đồng Tháp');